name: 1_Create PR from selected branch to main

on:
  workflow_dispatch:

jobs:
  create-pull-request-release2main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: "create-pr"
        branch: ${{ github.ref_name }}
        base: main
        title: "Merge ${{ github.ref_name }} into main"
        body: "This PR was automatically created by GitHub Actions."
        draft: false
        token: ${{ secrets.GITHUB_TOKEN }}
        