name: 1_Create PR from selected branch to main

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  create-pull-request-release2main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create Pull Request
      run: |
        # Install GitHub CLI
        sudo apt-get update
        sudo apt-get install gh

        # Authenticate with GitHub CLI
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

        # Create pull request
        gh pr create --base main --head ${{ github.ref_name }} --title "Merge ${{ github.ref_name }} into main" --body "This PR was automatically created by GitHub Actions."
