name: Tag Latest Commit and Create PR

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Name of the tag'
        required: true
        type: string

jobs:
  create-pull-request-main2develop:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install gh

    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Create Pull Request
      run: |
        gh pr create \
          --base develop \
          --head main \
          --title "Merge main into develop" \
          --body "This PR was automatically created by GitHub Actions."

  tag_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create tag
        run: |
          git fetch --tags
          git tag -a ${{ github.event.inputs.tag_name }} -m "Tagging commit ${{ github.sha }}"
          git push origin ${{ github.event.inputs.tag_name }}
