name: Tag Latest Commit

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Name of the tag'
        required: true
        type: string

jobs:
  create-pull-request-main2develop:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        branch: main # Source branch
        base: develop # Destination branch
        title: "Merge main into develop"
        body: "This PR was automatically created by GitHub Actions."
        draft: false
        token: ${{ secrets.GITHUB_TOKEN }}

  tag_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create tag
        run: |
          git fetch --tags
          git tag -a ${{ github.event.inputs.tag_name }} -m "Tagging commit ${{ github.sha }}"
          git push origin ${{ github.event.inputs.tag_name }}
